---
- name: Ensure config directory exists
  file:
    path: "{{ tessera_config_dir }}"
    state: directory
    owner: "{{ tessera_user }}"
    group: "{{ tessera_group }}"
  become: yes

- name: Generate config file
  template:
    src: "templates/config.json.j2"
    dest: "{{ tessera_config_dir }}/config.json"
    owner: "{{ tessera_user }}"
    group: "{{ tessera_group }}"
  become: true
  register: tessera_conf


...