---
- name: Ensure config directory exists
  file:
    path: "{{ tessera_config_dir }}"
    state: directory
    owner: "{{ tessera_user }}"
    group: "{{ tessera_group }}"
  become: yes

- name: Generate config file
  template:
    src: "tessera/templates/config.json.j2"
    dest: "{{ tessera_config_dir }}/tessera.conf"
    owner: "{{ tessera_user }}"
    group: "{{ tessera_group }}"
  become: true
  register: tessera_conf

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    tessera_state_updates: "{{ tessera_state_updates + ['tessera.tessera_conf'] }}"
  when: tessera_conf is changed

...