---
- name: Ensure we have tessera_version
  fail:
    msg: You must set "tessera_version" for this role to run
  when: tessera_version is not defined

- name: Install Dependencies
  include_tasks: "dependencies.yml"

- name: Install Tessera
  include_tasks: "install.yml"

- name: Install libsodium
  include_tasks: "install-libsodium.yml"

- name: Get private IP address to bind to if not provided
  include_tasks: "network_private.yml"
  when: tessera_client_ip is not defined

- name: Create config
  include_tasks: "config.yml"

- name: Create Tessera Service
  include_tasks: "service.yml"

...