---
- name: Create Tessera systemd service
  template:
    src: tessera/templates/tessera.service.j2
    dest: /etc/systemd/system/tessera.service
    owner: "root"
    group: "root"
  become: true
  when: ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    orion_state_updates: "{{ tessera_state_updates + ['tessera.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start Tessera service
  systemd:
    name: tessera
    state: restarted
    enabled: true
  become: true
  when: ( tessera_state_updates|length > 0 ) and ( ansible_os_family != "Darwin" )

...