---
- name: Create Tessera systemd service
  template:
    src: tessera/templates/tessera.service.j2
    dest: /etc/systemd/system/tessera.service
    owner: "root"
    group: "root"
  become: true
  when: ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start Tessera service
  systemd:
    name: tessera
    state: restarted
    enabled: true
  become: true

...